### ISSUE TITLE
Save entropy graph without connecting to $DISPLAY using python API

### ISSUE THREAD

**Issue by carlospolop** [ReFirmLabs/binwalk#304]
I have seen that if you execute in the shell: $ binwalk -E -J /path/IMAGE or if you use the python API with the params: ("/path/image", entropy=True, save=True) in a server that is not connected to any Display then an error occurs and the graph is not saved:

Entropy Exception: no display name and no $DISPLAY environment variable
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/module.py", line 597, in main
    retval = self.run()
  File "/usr/local/lib/python2.7/dist-packages/binwalk/modules/entropy.py", line 122, in run
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/binwalk/modules/entropy.py", line 138, in _run
    self.calculate_file_entropy(fp)
  File "/usr/local/lib/python2.7/dist-packages/binwalk/modules/entropy.py", line 212, in calculate_file_entropy
    self.plot_entropy(fp.name)
  File "/usr/local/lib/python2.7/dist-packages/binwalk/modules/entropy.py", line 263, in plot_entropy
    fig = plt.figure()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 534, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backend_bases.py", line 170, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 1049, in new_figure_manager_given_figure
    window = Tk.Tk(className="matplotlib")
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1823, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable
----------------------------------------------------------------------------------------------------

I still don't know if it is possible but if it is, would you accept a pull request where in case: "save"==True, then binwalk would save the image even if there isn't any display to connect to?

**Comment by carlospolop** [comment]
Thanks for the quick fix
