### ISSUE TITLE
TypeError: can't pickle int objects

### ISSUE THREAD

**Issue by brunoaduarte** [ReFirmLabs/binwalk#326]
```
ubuntu@ubuntu:~/binwalk-master$ binwalk /home/AthSDK/image/DAP1520A1_FW106B04.bin
Traceback (most recent call last):
  File "/usr/local/bin/binwalk", line 57, in <module>
    main()
  File "/usr/local/bin/binwalk", line 36, in main
    elif not modules.execute():
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 785, in execute
    obj = self.run(module)
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 804, in run
    obj = self.load(module, kwargs)
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 835, in load
    argv.update(self.dependencies(module, argv['enabled']))
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 862, in dependencies
    depobj = self.run(dependency.module, dependency=True, kwargs=dependency.kwargs)
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 804, in run
    obj = self.load(module, kwargs)
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 836, in load
    return module(self, **argv)
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 254, in __init__
    process_kwargs(self, kwargs)
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 1009, in process_kwargs
    kwargs = m.kwargs(obj, kwargs)
  File "/usr/local/lib/python2.6/dist-packages/binwalk/core/module.py", line 972, in kwargs
    arg_value = copy(module_argument.default)
  File "/usr/lib/python2.6/copy.py", line 87, in copy
    rv = reductor(2)
  File "/usr/lib/python2.6/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle int objects
```

**Comment by decidedlygray** [comment]
I grabbed a copy of what I assume is the same `DAP1520A1_FW106B04.bin` firmware from here: http://files.dlink.com.au/Products/DAP-1520/REV_A/Firmware/v1.06b04_06012015/

Using the latest `binwalk` with that firmware, extraction works as expected:
```
dg@ubuntu:~/workspace/binwalk_issue_326$ binwalk DAP1520A1_FW106B04.bin 

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             uImage header, header size: 64 bytes, header CRC: 0xBA3B64BA, created: 2015-01-22 03:48:48, image size: 909200 bytes, Data Address: 0x80000000, Entry Point: 0x8000C310, data CRC: 0x310BA125, OS: Linux, CPU: MIPS, image type: OS Kernel Image, compression type: lzma, image name: "Linux Kernel Image"
64            0x40            LZMA compressed data, properties: 0x5D, dictionary size: 33554432 bytes, uncompressed size: 2798288 bytes
983040        0xF0000         Squashfs filesystem, little endian, version 4.0, compression:xz, size: 3460300 bytes, 649 inodes, blocksize: 65536 bytes, created: 2015-01-22 03:48:54

dg@ubuntu:~/workspace/binwalk_issue_326$ binwalk -e DAP1520A1_FW106B04.bin 

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             uImage header, header size: 64 bytes, header CRC: 0xBA3B64BA, created: 2015-01-22 03:48:48, image size: 909200 bytes, Data Address: 0x80000000, Entry Point: 0x8000C310, data CRC: 0x310BA125, OS: Linux, CPU: MIPS, image type: OS Kernel Image, compression type: lzma, image name: "Linux Kernel Image"
64            0x40            LZMA compressed data, properties: 0x5D, dictionary size: 33554432 bytes, uncompressed size: 2798288 bytes
983040        0xF0000         Squashfs filesystem, little endian, version 4.0, compression:xz, size: 3460300 bytes, 649 inodes, blocksize: 65536 bytes, created: 2015-01-22 03:48:54
```

Likely binwalk was not properly installed, or this bug has been squashed by a fix since this ticket was opened
