### ISSUE TITLE
binwalk crashes when it is called by supervisor

### ISSUE THREAD

**Issue by jingleyang** [ReFirmLabs/binwalk#328]
The scenario is that my program uses binwalk python library and it is managed by supervisor(http://supervisord.org/). The binwalk will throw a exception when my program is loaded. The debug information is attached.

```
Traceback (most recent call last):
  File "", line , in 
    for module in binwalk.scan(filepath,signature=True):
  File "lib/python2.7/site-packages/binwalk/__init__.py", line 10, in scan
    objs = m.execute()
  File "lib/python2.7/site-packages/binwalk/core/module.py", line 784, in execute
    for module in self.list():
  File "lib/python2.7/site-packages/binwalk/core/module.py", line 710, in list
    user_modules = binwalk.core.settings.Settings().user.modules
  File "lib/python2.7/site-packages/binwalk/core/settings.py", line 39, in __init__
    self.user_dir = self._get_user_config_dir()
  File "lib/python2.7/site-packages/binwalk/core/settings.py", line 123, in _get_user_config_dir
    return os.path.join(self._get_user_dir(), '.config')
  File "lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
```
I studied the source code and the problem maybe  exists in the function `self._get_user_dir()`. The function will return None when the program is loaded by supervisor. Because the supervisor will not pass environment variables $HOME by default. And in this situation, the function `_get_user_dir()` will return None. Finally, a AttributeError execption will be thrown.

I will try to provide a pull request later. 

Thanks

**Comment by devttys0** [comment]
Commit d8f0edfc704a83c1d8e73f1d85890ae1dbeeda1d should fix this, please confirm.
