### ISSUE TITLE
Entropy plot generation failing

### ISSUE THREAD

**Issue by fabiolanza** [ReFirmLabs/binwalk#386]
Hi, I am trying to get an entropy plot from Binwalk, but it is not working. Please have a look at the error:
```
`root@fabio:~/Documents/stm32ldump# binwalk -E -J flash.bin 

DECIMAL       HEXADECIMAL     ENTROPY
--------------------------------------------------------------------------------
0             0x0             Falling entropy edge (0.740795)
8192          0x2000          Falling entropy edge (0.783186)
46080         0xB400          Falling entropy edge (0.782712)
172032        0x2A000         Falling entropy edge (0.783186)
209920        0x33400         Falling entropy edge (0.782712)
221184        0x36000         Falling entropy edge (0.635223)
225280        0x37000         Falling entropy edge (0.777494)
230400        0x38400         Falling entropy edge (0.656148)
236544        0x39C00         Falling entropy edge (0.627715)
238592        0x3A400         Falling entropy edge (0.833950)

Entropy Exception: 'float' object cannot be interpreted as an integer
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/binwalk/core/module.py", line 566, in main
    retval = self.run()
  File "/usr/lib/python3/dist-packages/binwalk/modules/entropy.py", line 122, in run
    self._run()
  File "/usr/lib/python3/dist-packages/binwalk/modules/entropy.py", line 138, in _run
    self.calculate_file_entropy(fp)
  File "/usr/lib/python3/dist-packages/binwalk/modules/entropy.py", line 214, in calculate_file_entropy
    self.plot_entropy(fp.name)
  File "/usr/lib/python3/dist-packages/binwalk/modules/entropy.py", line 309, in plot_entropy
    exporter.export(binwalk.core.common.unique_file_name(out_file, self.FILE_FORMAT))
  File "/usr/lib/python3/dist-packages/pyqtgraph/exporters/ImageExporter.py", line 70, in export
    bg = np.empty((self.params['width'], self.params['height'], 4), dtype=np.ubyte)
TypeError: 'float' object cannot be interpreted as an integer
----------------------------------------------------------------------------------------------------

```

Would this have an easy fix? Thanks.`

**Comment by unattributed** [comment]
This is long fixed in master. Unfortunately there hasn't been a release in nearly 4 years...
