### ISSUE TITLE
Failed installation on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by gergelykalman** [ReFirmLabs/binwalk#41]
I installed binwalk according to the instructions in INSTALL, everything went fine, but when I start binwalk with a firmware file it gives me this:

WARNING: Failed to load plugin module 'compressd': Failed to locate library 'compress42'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate library 'tinfl'

WARNING: Failed to load plugin module 'compressd': Failed to locate library 'compress42'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate library 'tinfl'
## Signature Exception: Failed to locate library 'inmagic'

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/module.py", line 475, in main
    self.init()
  File "/usr/local/lib/python2.7/dist-packages/binwalk/modules/signature.py", line 85, in init
    self.magic = binwalk.core.magic.Magic(self.mfile)
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/magic.py", line 41, in **init**
    self.libmagic = binwalk.core.C.Library("inmagic", self.LIBMAGIC_FUNCTIONS)
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/C.py", line 99, in **init**
    self.library = ctypes.cdll.LoadLibrary(self.find_library(library))
  File "/usr/local/lib/python2.7/dist-packages/binwalk/core/C.py", line 137, in find_library
    raise Exception("Failed to locate library '%s'" % library)

**Comment by sirus20x6** [comment]
I still have this issue on windows 10

**Comment by hackerjj** [comment]
In the installation folder src/binwalk/libs/ doesn't comes anything. :S

**Comment by hackerjj** [comment]
Aleady get it.

First in installation folder run:

./configure
Then
make
Last:
sudo make install

Copy libs inside src/binwalk/libs folder into /usr/local/lib/ like sneaky said and wuala...

BR. Thankx!!!
