### ISSUE TITLE
A bug in binwalk/core/settings.py, line 135

### ISSUE THREAD

**Issue by gal0is** [ReFirmLabs/binwalk#413]
I encountered a error as follows:
```
Traceback (most recent call last):
  File "./sources/extractor/extractor.py", line 18, in <module>
    import binwalk
  File "/root/deep/anaconda3/envs/iot/lib/python3.7/site-packages/binwalk/__init__.py", line 3, in <module>
    from binwalk.core.module import Modules
  File "/root/deep/anaconda3/envs/iot/lib/python3.7/site-packages/binwalk/core/module.py", line 17, in <module>
    import binwalk.core.settings
  File "/root/deep/anaconda3/envs/iot/lib/python3.7/site-packages/binwalk/core/settings.py", line 135
    if os.path.expanduser("~") is Not None:
                                         ^
SyntaxError: invalid syntax
```

I think this might be a typo in settings.py :)
The 'Not' should be 'not'

```
135  if os.path.expanduser("~") is Not None:
136      return os.path.expanduser("~")
```

**Comment by devttys0** [comment]
Yep, this was a typo, it's been fixed in master. Thanks!
