### ISSUE TITLE
[MAC] ImportError: No module named core.module

### ISSUE THREAD

**Issue by johneric8828** [ReFirmLabs/binwalk#455]
Having an issue with binwalk saying no module named core.module after installation of binwalk. I've tried "pip install binwalk" "brew install binwalk" I've even installed ran the install from the git master file, nothing seems to fix this issue. 

Has anyone fixed this, or know how to fix this? 

I've tried everything in the previous posts. 

> MacBook-Pro:binwalk-master Eric$ binwalk
> Traceback (most recent call last):
>   File "/usr/local/bin/binwalk", line 25, in <module>
>     import binwalk
>   File "/Users/Eric/Library/Python/2.7/lib/python/site-packages/binwalk/__init__.py", line 3, in <module>
>     from binwalk.core.module import Modules, ModuleException
> ImportError: No module named core.module
>

**Comment by johneric8828** [comment]
It seems the Quick Setup Guide was able to fix this somehow, which I don't see how it is any different. It seems the symlink was in the wrong location. I had to remove the old symlink location by using the command below. 

`rm '/usr/local/bin/binwalk'`

-------------------
> Warning: binwalk 2.2.0_1 is already installed, it's just not linked
> You can use `brew link binwalk` to link this version.
> MacBook-Pro:~ Eric$ brew link binwalk
> Linking /usr/local/Cellar/binwalk/2.2.0_1... 
> Error: Could not symlink bin/binwalk
> Target /usr/local/bin/binwalk
> already exists. You may want to remove it:
>   rm '/usr/local/bin/binwalk'
> 
> To force the link and overwrite all conflicting files:
>   brew link --overwrite binwalk
> 
> To list all files that would be deleted:
>   brew link --overwrite --dry-run binwalk
> MacBook-Pro:~ Eric$ rm '/usr/local/bin/binwalk'
> override rwxr-xr-x  root/admin for /usr/local/bin/binwalk? yes
> MacBook-Pro:~ Eric$ brew link binwalk
> Linking /usr/local/Cellar/binwalk/2.2.0_1... 1 symlinks created
