### ISSUE TITLE
Uninstall error

### ISSUE THREAD

**Issue by RiotGamesU** [ReFirmLabs/binwalk#501]
platform:windows10
python version:python3.9.0
binwalk version:latest

Use "python setup.py install " to install binwalk, and when I want to uninstall binwalk:

C:\binwalk\binwalk-master>python setup.py uninstall
running uninstall
removing 'C:\python\Python39\lib\site-packages\binwalk' (and everything under it)
Traceback (most recent call last):
  File "C:\binwalk\binwalk-master\setup.py", line 322, in <module>
    setup(
  File "C:\python\Python39\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\python\Python39\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\python\Python39\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\binwalk\binwalk-master\setup.py", line 209, in run
    remove_binwalk_module(self.pydir, self.pybin)
  File "C:\binwalk\binwalk-master\setup.py", line 86, in remove_binwalk_module
    pybin = which(MODULE_NAME)
  File "C:\binwalk\binwalk-master\setup.py", line 53, in which
    if not location and os.path.exists(usr_local_bin):
UnboundLocalError: local variable 'location' referenced before assignment

**Comment by dragonfire-git** [comment]
my error is UnboundLocalError: cannot access local variable 'location' where it is not associated with a value
