### ISSUE TITLE
ModuleNotFoundError: No module named 'binwalk.core'

### ISSUE THREAD

**Issue by vadimszzz** [ReFirmLabs/binwalk#589]
Typed:
```bash
$ pip install binwalk
Collecting binwalk
  Using cached binwalk-2.1.0-py3-none-any.whl
Installing collected packages: binwalk
Successfully installed binwalk-2.1.0
$
```
Then:
```python
import binwalk
```

```
Traceback (most recent call last):
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/x/Downloads/Projects/ios-apps-research-2021/exynex/__main__.py", line 11, in <module>
    from exynex.cli.analyze import cli as analyze_cli
  File "/Users/x/Downloads/Projects/ios-apps-research-2021/exynex/cli/analyze.py", line 13, in <module>
    import binwalk
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/binwalk/__init__.py", line 3, in <module>
    from binwalk.core.module import Modules, ModuleException
ModuleNotFoundError: No module named 'binwalk.core'
```

**Comment by vadimszzz** [comment]
https://github.com/ReFirmLabs/binwalk/issues/352
