### ISSUE TITLE
binwalk error

### ISSUE THREAD

**Issue by javelineou** [ReFirmLabs/binwalk#611]
Hi, i just installed binwalk using these command below
``sudo apt install binwalk``
then followed with
```
git clone https://github.com/ReFirmLabs/binwalk.git
cd binwalk
sudo python setup.py install
```

then i tried to run it but this error appeared.
```
Traceback (most recent call last):
  File "/usr/bin/binwalk", line 2, in <module>
    from binwalk.__main__ import main
  File "/usr/local/lib/python3.10/dist-packages/binwalk-2.3.3+fa0c0bd-py3.10.egg/binwalk/__main__.py", line 24, in <module>
    import binwalk.modules
  File "/usr/local/lib/python3.10/dist-packages/binwalk-2.3.3+fa0c0bd-py3.10.egg/binwalk/modules/__init__.py", line 17, in <module>
    from binwalk.modules.entropy import Entropy
  File "/usr/local/lib/python3.10/dist-packages/binwalk-2.3.3+fa0c0bd-py3.10.egg/binwalk/modules/entropy.py", line 16, in <module>
    from numba import njit
  File "/usr/lib/python3/dist-packages/numba/__init__.py", line 38, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "/usr/lib/python3/dist-packages/numba/core/decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "/usr/lib/python3/dist-packages/numba/stencils/stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "/usr/lib/python3/dist-packages/numba/core/registry.py", line 4, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "/usr/lib/python3/dist-packages/numba/core/dispatcher.py", line 13, in <module>
    from numba.core import (
  File "/usr/lib/python3/dist-packages/numba/core/compiler.py", line 6, in <module>
    from numba.core import (utils, errors, typing, interpreter, bytecode, postproc,
  File "/usr/lib/python3/dist-packages/numba/core/callconv.py", line 12, in <module>
    from numba.core.base import PYOBJECT, GENERIC_POINTER
  File "/usr/lib/python3/dist-packages/numba/core/base.py", line 1266, in <module>
    _initialize_llvm_lock_event()
  File "/usr/lib/python3/dist-packages/numba/core/utils.py", line 446, in inner
    res = fn()
  File "/usr/lib/python3/dist-packages/numba/core/base.py", line 1263, in _initialize_llvm_lock_event
    ll.ffi.register_lock_callback(enter_fn, exit_fn)
AttributeError: module 'llvmlite.binding.ffi' has no attribute 'register_lock_callback'

```

any idea how to solve it?

**Comment by mzpqnxow** [comment]
I'm not affiliated with binwalk aside from being a user, but I recommend the following:

1. Uninstall the binwalk OS package and never install it again
2. Create a fresh virtualenv (mkdir venv && virtualenv venv)
3. Enter the virtualenv (source benv/bin/activate
4. Install binwalk from github via pip (pip install "git+https://github.com/devTTYS0/binwalk@master")
5. All done
