### ISSUE TITLE
AttributeError: module 'capstone' has no attribute 'CS_ARCH_ARM64'

### ISSUE THREAD

**Issue by 1392081456** [ReFirmLabs/binwalk#688]
System information：Linux kali 6.10.9-amd64 #1 SMP PREEMPT_DYNAMIC Kali 6.10.9-1kali1 (2024-09-09) x86_64 GNU/Linux
python information:   3.12.6

When I run binwalk, it appears：
Traceback (most recent call last):
  File "/usr/bin/binwalk", line 33, in <module>
    sys.exit(load_entry_point('binwalk==2.4.2', 'console_scripts', 'binwalk')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/binwalk", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/binwalk/__main__.py", line 24, in <module>
    import binwalk.modules
  File "/usr/lib/python3/dist-packages/binwalk/modules/__init__.py", line 3, in <module>
    from binwalk.modules.disasm import Disasm
  File "/usr/lib/python3/dist-packages/binwalk/modules/disasm.py", line 21, in <module>
    class Disasm(Module):
  File "/usr/lib/python3/dist-packages/binwalk/modules/disasm.py", line 60, in Disasm
    Architecture(type=capstone.CS_ARCH_ARM64,
                      ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'capstone' has no attribute 'CS_ARCH_ARM64'. Did you mean: 'CS_ARCH_ARM'?

I try to update binwalk，but it is the newest.  Then I followed the instructions to find the corresponding disasm.py and modify it。I modify the "ARM64" to "ARM",   just like：
ARCHITECTURES =[
Architecture(type=capstone.CS_ARCH_ARM,
mode=capstone.CS_MoDE_ARM,
endiannesS=capstone.CS_MODE_BIG_ENDIAN,
description="ARM executable code, 32-bit, big endian"),
Architecture(type=capstone.CS_ARCH_ARM,
mode=capstone.CS_MoDE_ARM,
endiannesS=capstone.CS_MODE_LITTLE_ENDIAN,
description="ARM executable code, 32-bit, little endian"),
Architecture(type=capstone.CS_ARCH_ARM,
mode=capstone.CS_MODE_ARM,
endianness=capstone.CS_MODE_BIG_ENDIAN,
description="ARM executable code, 64-bit, big endian"),
Architecture(type=capstone.CS_ARCH_ARM,
mode=capstone.CS_MODE_ARM,
romendiannesS=capstone.CS_MODE_LITTLE_ENDIAN,
Devicesdescription="ARM executable code, 64-bit, little endian"),

binwalk is then ready to run。

I would like to know why this is, and does my modification affect binwalk?

**Comment by 1392081456** [comment]
Do I need to uninstall it and reinstall it？

**Comment by devttys0** [comment]
It looks like this error is due to a change to the Capstone API.

Your patch will only affect CPU opcode detection (`--opcodes`) for ARM: you won't be able to detect ARM64, and/or ARM32 may be reported as ARM64.

Note that current development efforts are focused on [Binwalkv3](https://github.com/ReFirmLabs/binwalk/tree/binwalkv3), which no longer supports the `--opcodes` argument. As a replacement I recommend the [cpu_rec](https://github.com/trou/cpu_rec_rs) tool, which is much better for identifying raw CPU instructions in a file.

**Comment by 1392081456** [comment]
Thank you for your reply！ The version of capstone I found is (6.0.0a1)，which version is more suitable?

**Comment by CdcEta** [comment]
Have you solved the problem? I got this wrong, too.

**Comment by Yo1o-sir** [comment]
So how to solve this problem?

**Comment by LoveSunday7** [comment]
这老外有点无语了，把问题发出来不解决

**Comment by LoveSunday7** [comment]
这老外有点牛逼哈，我也改好了

**Comment by liudonghua123** [comment]
I have the same error when using binwalk on kali.

```
┌──(liudonghua㉿LDH-DESKTOP)-[~]
└─$ binwalk '/mnt/d/Downloads/running/run.exe'
Traceback (most recent call last):
  File "/usr/bin/binwalk", line 2, in <module>
    from binwalk.__main__ import main
  File "/usr/lib/python3/dist-packages/binwalk/__main__.py", line 24, in <module>
    import binwalk.modules
  File "/usr/lib/python3/dist-packages/binwalk/modules/__init__.py", line 3, in <module>
    from binwalk.modules.disasm import Disasm
  File "/usr/lib/python3/dist-packages/binwalk/modules/disasm.py", line 21, in <module>
    class Disasm(Module):
  File "/usr/lib/python3/dist-packages/binwalk/modules/disasm.py", line 60, in Disasm
    Architecture(type=capstone.CS_ARCH_ARM64,
                      ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'capstone' has no attribute 'CS_ARCH_ARM64'. Did you mean: 'CS_ARCH_ARM'?

```

And I have tried the following two methods. Both of them works for me.

1. install the latest binwalk v3 via `cargo install binwalk`
2. install the latest [capstone](https://pypi.org/project/capstone/) v5 via `pip install capstone` or `sudo apt install python3-capstone`.

<details><summary>Details</summary>

```
┌──(liudonghua㉿LDH-DESKTOP)-[~/ctf]
└─$ cargo install binwalk
......
┌──(liudonghua㉿LDH-DESKTOP)-[~/ctf]
└─$ which binwalk
/home/liudonghua/.cargo/bin/binwalk

┌──(liudonghua㉿LDH-DESKTOP)-[/mnt/d/Downloads/running]
└─$ binwalk run.exe

                                            /mnt/d/Downloads/running/run.exe
------------------------------------------------------------------------------------------------------------------------
DECIMAL                            HEXADECIMAL                        DESCRIPTION
------------------------------------------------------------------------------------------------------------------------
0                                  0x0                                Windows PE binary, machine type: Intel x86
199872                             0x30CC0                            PNG image, total size: 2885 bytes
202760                             0x31808                            PNG image, total size: 5545 bytes
230692                             0x38524                            PNG image, total size: 15729 bytes
429056                             0x68C00                            ZIP archive, file count: 2, total size: 259512
                                                                      bytes
------------------------------------------------------------------------------------------------------------------------

Analyzed 1 file for 85 file signatures (187 magic patterns) in 12.0 milliseconds

┌──(liudonghua㉿LDH-DESKTOP)-[/mnt/d/Downloads/running]
└─$ pip install capstone
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.

    See /usr/share/doc/python3.13/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
┌──(liudonghua㉿LDH-DESKTOP)-[/mnt/d/Downloads/running]
└─$ sudo apt install python3-capstone
The following packages were automatically installed and are no longer required:
  liblbfgsb0  libpython3.11-dev  python3-lib2to3  python3.11  python3.11-dev  python3.11-minimal
Use 'sudo apt autoremove' to remove them.

Installing:
  python3-capstone

Installing dependencies:
  libcapstone5

Summary:
  Upgrading: 0, Installing: 2, Removing: 0, Not Upgrading: 1449
  Download size: 907 kB
  Space needed: 10.2 MB / 1,014 GB available

Continue? [Y/n]
Get:1 https://mirrors.tuna.tsinghua.edu.cn/kali kali-rolling/main amd64 libcapstone5 amd64 5.0.6-1 [780 kB]
Get:2 https://mirrors.tuna.tsinghua.edu.cn/kali kali-rolling/main amd64 python3-capstone amd64 5.0.6-1 [126 kB]
Fetched 907 kB in 1s (670 kB/s)
Selecting previously unselected package libcapstone5:amd64.
(Reading database ... 208954 files and directories currently installed.)
Preparing to unpack .../libcapstone5_5.0.6-1_amd64.deb ...
Unpacking libcapstone5:amd64 (5.0.6-1) ...
Selecting previously unselected package python3-capstone.
Preparing to unpack .../python3-capstone_5.0.6-1_amd64.deb ...
Unpacking python3-capstone (5.0.6-1) ...
Setting up libcapstone5:amd64 (5.0.6-1) ...
Setting up python3-capstone (5.0.6-1) ...
Processing triggers for libc-bin (2.38-13) ...

┌──(liudonghua㉿LDH-DESKTOP)-[/mnt/d/Downloads/running]
└─$ /usr/bin/binwalk run.exe

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
0             0x0             Microsoft executable, portable (PE)
199872        0x30CC0         PNG image, 93 x 302, 8-bit/color RGB, non-interlaced
200031        0x30D5F         Zlib compressed data, best compression
202760        0x31808         PNG image, 186 x 604, 8-bit/color RGB, non-interlaced
202900        0x31894         Zlib compressed data, best compression
230692        0x38524         PNG image, 256 x 256, 8-bit/color RGBA, non-interlaced
230733        0x3854D         Zlib compressed data, best compression
416440        0x65AB8         XML document, version: "1.0"
429056        0x68C00         Zip archive data, at least v2.0 to extract, compressed size: 9413, uncompressed size: 11001, name: New Microsoft Word Document.docx
438531        0x6B103         Zip archive data, at least v2.0 to extract, compressed size: 249667, uncompressed size: 367616, name: run.exe


┌──(liudonghua㉿LDH-DESKTOP)-[/mnt/d/Downloads/running]
└─$
┌──(liudonghua㉿LDH-DESKTOP)-[/mnt/d/Downloads/running]
└─$ /usr/bin/binwalk -V

┌──(liudonghua㉿LDH-DESKTOP)-[/mnt/d/Downloads/running]
└─$ /usr/bin/binwalk -h

Binwalk v2.3.3
Craig Heffner, ReFirmLabs
https://github.com/ReFirmLabs/binwalk

Usage: binwalk [OPTIONS] [FILE1] [FILE2] [FILE3] ...

Disassembly Scan Options:
    -Y, --disasm                 Identify the CPU architecture of a file using the capstone disassembler
    -T, --minsn=<int>            Minimum number of consecutive instructions to be considered valid (default: 500)
    -k, --continue               Don't stop at the first match

Signature Scan Options:
    -B, --signature              Scan target file(s) for common file signatures
    -R, --raw=<str>              Scan target file(s) for the specified sequence of bytes
    -A, --opcodes                Scan target file(s) for common executable opcode signatures
    -m, --magic=<file>           Specify a custom magic file to use
    -b, --dumb                   Disable smart signature keywords
    -I, --invalid                Show results marked as invalid
    -x, --exclude=<str>          Exclude results that match <str>
    -y, --include=<str>          Only show results that match <str>

Extraction Options:
    -e, --extract                Automatically extract known file types
    -D, --dd=<type[:ext[:cmd]]>  Extract <type> signatures (regular expression), give the files an extension of <ext>, and execute <cmd>
    -M, --matryoshka             Recursively scan extracted files
    -d, --depth=<int>            Limit matryoshka recursion depth (default: 8 levels deep)
    -C, --directory=<str>        Extract files/folders to a custom directory (default: current working directory)
    -j, --size=<int>             Limit the size of each extracted file
    -n, --count=<int>            Limit the number of extracted files
    -0, --run-as=<str>           Execute external extraction utilities with the specified user's privileges
    -1, --preserve-symlinks      Do not sanitize extracted symlinks that point outside the extraction directory (dangerous)
    -r, --rm                     Delete carved files after extraction
    -z, --carve                  Carve data from files, but don't execute extraction utilities
    -V, --subdirs                Extract into sub-directories named by the offset

Entropy Options:
    -E, --entropy                Calculate file entropy
    -F, --fast                   Use faster, but less detailed, entropy analysis
    -J, --save                   Save plot as a PNG
    -Q, --nlegend                Omit the legend from the entropy plot graph
    -N, --nplot                  Do not generate an entropy plot graph
    -H, --high=<float>           Set the rising edge entropy trigger threshold (default: 0.95)
    -L, --low=<float>            Set the falling edge entropy trigger threshold (default: 0.85)

Binary Diffing Options:
    -W, --hexdump                Perform a hexdump / diff of a file or files
    -G, --green                  Only show lines containing bytes that are the same among all files
    -i, --red                    Only show lines containing bytes that are different among all files
    -U, --blue                   Only show lines containing bytes that are different among some files
    -u, --similar                Only display lines that are the same between all files
    -w, --terse                  Diff all files, but only display a hex dump of the first file

Raw Compression Options:
    -X, --deflate                Scan for raw deflate compression streams
    -Z, --lzma                   Scan for raw LZMA compression streams
    -P, --partial                Perform a superficial, but faster, scan
    -S, --stop                   Stop after the first result

General Options:
    -l, --length=<int>           Number of bytes to scan
    -o, --offset=<int>           Start scan at this file offset
    -O, --base=<int>             Add a base address to all printed offsets
    -K, --block=<int>            Set file block size
    -g, --swap=<int>             Reverse every n bytes before scanning
    -f, --log=<file>             Log results to file
    -c, --csv                    Log results to file in CSV format
    -t, --term                   Format output to fit the terminal window
    -q, --quiet                  Suppress output to stdout
    -v, --verbose                Enable verbose output
    -h, --help                   Show help output
    -a, --finclude=<str>         Only scan files whose names match this regex
    -p, --fexclude=<str>         Do not scan files whose names match this regex
    -s, --status=<int>           Enable the status server on the specified port


┌──(liudonghua㉿LDH-DESKTOP)-[/mnt/d/Downloads/running]
└─$
```

</details>

**Comment by shiria1207** [comment]
thanks bro, i just do this and it works too
        # Architecture(type=capstone.CS_ARCH_ARM64,
        #              mode=capstone.CS_MODE_ARM,
        #              endianness=capstone.CS_MODE_BIG_ENDIAN,
        #              description="ARM executable code, 64-bit, big endian"),
        # Architecture(type=capstone.CS_ARCH_ARM64,
        #              mode=capstone.CS_MODE_ARM,
        #              endianness=capstone.CS_MODE_LITTLE_ENDIAN,
        #              description="ARM executable code, 64-bit, little endian"),
